# Generated by Django 4.2a1 on 2023-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome_do_Animal",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome_do_Dono",
            field=models.CharField(max_length=100),
        ),
    ]
