# Generated by Django 4.2a1 on 2023-02-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_alter_paciente_cpf_alter_paciente_nome_do_animal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="nome_do_Animal",
            new_name="nome_do_animal",
        ),
        migrations.RenameField(
            model_name="paciente",
            old_name="nome_do_Dono",
            new_name="nome_do_dono",
        ),
    ]
