# Generated by Django 4.2a1 on 2023-02-04 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "receituario",
                    models.CharField(max_length=200, verbose_name="Receituário"),
                ),
                ("exame", models.CharField(max_length=100, verbose_name="Exames")),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
            ],
        ),
    ]
